"""Constantes y utilidades del RBAC configurable."""

PERM_ADMIN_ACCESO = "admin.acceso"
PERM_CONSOLIDADO_VER = "consolidado.ver"

PERMISOS_CATALOGO: list[str] = [
    "dashboard.ver",
    "dashboard.estados.ver",
    "dashboard.squad.ver",
    "requerimientos.ver",
    "requerimientos.detalle_ans.editar",
    "requerimientos.crear",
    "requerimientos.editar",
    "requerimientos.eliminar",
    "requerimientos.tipificacion.editar",
    "entregas_actas.ver",
    "entregas_actas.exportar",
    "requerimientos.exportar",
    "predictivos.ver",
    "personas.ver",
    "personas.crear",
    "personas.editar",
    "personas.eliminar",
    "asignaciones.ver",
    "asignaciones.editar",
    "capacidades.ver",
    "capacidades.editar",
    "control_horas_facturable.ver",
    "roadmap.ver",
    "azure_devops.ver",
    "azure_devops.editar",
    "estimaciones.ver",
    "facturacion.ver",
    "planes_accion.ver",
    "planes_accion.editar",
    "aplicaciones.ver",
    "aplicaciones.crear",
    "aplicaciones.editar",
    "admin.usuarios.ver",
    "admin.usuarios.crear",
    "admin.usuarios.editar",
    "admin.roles.ver",
    "admin.roles.crear",
    "admin.roles.editar",
    "admin.roles.eliminar",
    "admin.importacion.ver",
    "admin.importacion.ejecutar",
    "admin.endpoints.ver",
    "admin.endpoints.crear",
    "admin.endpoints.editar",
    "admin.endpoints.eliminar",
    "admin.configuracion.ver",
    "admin.configuracion.editar",
    "soporte.solicitudes_fabrica.ver",
    "soporte.solicitudes_fabrica.actualizar",
    "soporte.detalle_ans.editar",
    PERM_ADMIN_ACCESO,
    PERM_CONSOLIDADO_VER,
]

ROLES_BASE: list[dict] = [
    {
        "clave": "superadmin",
        "nombre": "Superadministrador",
        "descripcion": "Acceso total a todos los módulos, roles, permisos y squads.",
        "es_sistema": True,
        "permisos": ["*"],
    },
    {
        "clave": "admin_app",
        "nombre": "Administrador de squad",
        "descripcion": "Administra usuarios, datos y configuración operativa de sus squads asignados.",
        "es_sistema": True,
        "permisos": [
            "dashboard.ver",
            "dashboard.estados.ver",
            "dashboard.squad.ver",
            "requerimientos.ver",
            "entregas_actas.ver",
            "entregas_actas.exportar",
            "requerimientos.exportar",
            "predictivos.ver",
            "personas.ver",
            "personas.crear",
            "personas.editar",
            "personas.eliminar",
            "asignaciones.ver",
            "asignaciones.editar",
            "capacidades.ver",
            "capacidades.editar",
            "control_horas_facturable.ver",
            "roadmap.ver",
            "azure_devops.ver",
            "azure_devops.editar",
            "estimaciones.ver",
            "facturacion.ver",
            "planes_accion.ver",
            "planes_accion.editar",
            "aplicaciones.ver",
            "aplicaciones.editar",
            "admin.usuarios.ver",
            "admin.usuarios.crear",
            "admin.usuarios.editar",
            "admin.roles.ver",
            "admin.importacion.ver",
            "admin.importacion.ejecutar",
            "soporte.solicitudes_fabrica.ver",
            "soporte.solicitudes_fabrica.actualizar",
            "soporte.detalle_ans.editar",
            "requerimientos.detalle_ans.editar",
            "requerimientos.tipificacion.editar",
            PERM_ADMIN_ACCESO,
            PERM_CONSOLIDADO_VER,
        ],
    },
    {
        "clave": "viewer",
        "nombre": "Gerentes",
        "descripcion": "Consulta dashboards, requerimientos, soporte y facturación sin permisos de edición.",
        "es_sistema": True,
        "permisos": [
            "dashboard.ver",
            "dashboard.estados.ver",
            "dashboard.squad.ver",
            "requerimientos.ver",
            "entregas_actas.ver",
            "predictivos.ver",
            "personas.ver",
            "asignaciones.ver",
            "capacidades.ver",
            "control_horas_facturable.ver",
            "roadmap.ver",
            "estimaciones.ver",
            "facturacion.ver",
            "planes_accion.ver",
            "soporte.solicitudes_fabrica.ver",
        ],
    },
]


def normalizar_permisos(permisos: list[str]) -> list[str]:
    vistos: set[str] = set()
    resultado: list[str] = []
    for permiso in permisos:
        p = (permiso or "").strip()
        if not p:
            continue
        if p in vistos:
            continue
        vistos.add(p)
        resultado.append(p)
    return resultado
