import type { EndpointDoc, Metodo } from './tipos'

export const ENDPOINTS: EndpointDoc[] = [
  { modulo: 'Sistema', metodo: 'GET', ruta: '/api/health', descripcion: 'Verifica disponibilidad de la API.' },
  { modulo: 'Autenticación', metodo: 'POST', ruta: '/api/auth/login', descripcion: 'Autentica usuario y entrega JWT.', cuerpo: 'email, password' },
  { modulo: 'Autenticación', metodo: 'GET', ruta: '/api/auth/me', descripcion: 'Devuelve el usuario autenticado.' },

  { modulo: 'Aplicaciones', metodo: 'GET', ruta: '/api/aplicaciones', descripcion: 'Lista aplicaciones registradas.' },
  { modulo: 'Aplicaciones', metodo: 'POST', ruta: '/api/aplicaciones', descripcion: 'Crea una aplicación.', cuerpo: 'codigo, nombre, descripcion' },
  { modulo: 'Aplicaciones', metodo: 'PUT', ruta: '/api/aplicaciones/{codigo}', descripcion: 'Actualiza una aplicación.' },
  { modulo: 'Aplicaciones', metodo: 'PATCH', ruta: '/api/aplicaciones/{codigo}/estado', descripcion: 'Activa o desactiva una aplicación.', cuerpo: 'activa' },
  { modulo: 'Aplicaciones', metodo: 'GET', ruta: '/api/aplicaciones/{codigo}/usuarios', descripcion: 'Lista usuarios asociados a una aplicación.' },
  { modulo: 'Aplicaciones', metodo: 'POST', ruta: '/api/aplicaciones/{codigo}/usuarios/{usuario_id}', descripcion: 'Asocia un usuario a una aplicación.' },
  { modulo: 'Aplicaciones', metodo: 'DELETE', ruta: '/api/aplicaciones/{codigo}/usuarios/{usuario_id}', descripcion: 'Quita un usuario de una aplicación.' },

  { modulo: 'Usuarios y roles', metodo: 'GET', ruta: '/api/usuarios', descripcion: 'Lista usuarios.' },
  { modulo: 'Usuarios y roles', metodo: 'POST', ruta: '/api/usuarios', descripcion: 'Crea un usuario.', cuerpo: 'nombre, email, password, rol_id, aplicaciones' },
  { modulo: 'Usuarios y roles', metodo: 'PUT', ruta: '/api/usuarios/{usuario_id}', descripcion: 'Actualiza usuario, rol o estado.' },
  { modulo: 'Usuarios y roles', metodo: 'PATCH', ruta: '/api/usuarios/{usuario_id}/password', descripcion: 'Cambia contraseña de usuario.', cuerpo: 'password' },
  { modulo: 'Usuarios y roles', metodo: 'GET', ruta: '/api/roles/catalogo', descripcion: 'Lista permisos disponibles.' },
  { modulo: 'Usuarios y roles', metodo: 'GET', ruta: '/api/roles', descripcion: 'Lista roles.' },
  { modulo: 'Usuarios y roles', metodo: 'POST', ruta: '/api/roles', descripcion: 'Crea rol.', cuerpo: 'nombre, descripcion, permisos' },
  { modulo: 'Usuarios y roles', metodo: 'PUT', ruta: '/api/roles/{rol_id}', descripcion: 'Actualiza rol.' },
  { modulo: 'Usuarios y roles', metodo: 'DELETE', ruta: '/api/roles/{rol_id}', descripcion: 'Elimina rol.' },

  { modulo: 'Requerimientos', metodo: 'GET', ruta: '/api/requerimientos', descripcion: 'Lista requerimientos de la aplicación activa o consolidado.', parametros: 'estado opcional' },
  { modulo: 'Requerimientos', metodo: 'POST', ruta: '/api/requerimientos', descripcion: 'Crea requerimiento.', cuerpo: 'RequerimientoIn', permisos: 'requerimientos.crear' },
  { modulo: 'Requerimientos', metodo: 'GET', ruta: '/api/requerimientos/{codigo_req}', descripcion: 'Obtiene requerimiento por id o código REQ.' },
  { modulo: 'Requerimientos', metodo: 'PUT', ruta: '/api/requerimientos/{codigo_req}', descripcion: 'Actualiza campos del requerimiento.', cuerpo: 'RequerimientoUpdate', permisos: 'requerimientos.editar' },
  { modulo: 'Requerimientos', metodo: 'DELETE', ruta: '/api/requerimientos/{codigo_req}', descripcion: 'Elimina requerimiento y estimaciones asociadas.', permisos: 'requerimientos.eliminar' },
  { modulo: 'Requerimientos', metodo: 'POST', ruta: '/api/requerimientos/ans/calcular', descripcion: 'Calcula resultado ANS entre fechas.', cuerpo: 'fecha_inicio, fecha_fin, umbral_dias_habiles' },
  { modulo: 'Requerimientos', metodo: 'POST', ruta: '/api/requerimientos/{codigo_req}/transicion', descripcion: 'Cambia estado del requerimiento.', cuerpo: 'nuevo_estado, descripcion' },
  { modulo: 'Requerimientos', metodo: 'POST', ruta: '/api/requerimientos/{codigo_req}/entregas', descripcion: 'Agrega o reemplaza una entrega.' },
  { modulo: 'Requerimientos', metodo: 'DELETE', ruta: '/api/requerimientos/{codigo_req}/entregas/{numero}', descripcion: 'Elimina una entrega por número.' },
  { modulo: 'Requerimientos', metodo: 'GET', ruta: '/api/requerimientos/{codigo_req}/liquidacion', descripcion: 'Calcula liquidación del requerimiento.' },
  { modulo: 'Administración', metodo: 'GET', ruta: '/api/requerimientos/{codigo_req}/diagnostico', descripcion: 'Diagnóstico por REQ o SC en modo consolidado.', permisos: 'requerimientos.editar' },
  { modulo: 'Administración', metodo: 'POST', ruta: '/api/requerimientos/{codigo_req}/reasignar-aplicacion', descripcion: 'Reasigna un requerimiento a otra aplicación.', parametros: 'nueva_aplicacion', permisos: 'requerimientos.editar' },

  { modulo: 'Estimaciones', metodo: 'GET', ruta: '/api/estimaciones', descripcion: 'Lista estimaciones.' },
  { modulo: 'Estimaciones', metodo: 'GET', ruta: '/api/estimaciones/por-requerimiento/{requerimiento_id}', descripcion: 'Obtiene estimación y resumen por requerimiento.' },
  { modulo: 'Estimaciones', metodo: 'POST', ruta: '/api/estimaciones/upload/{requerimiento_id}', descripcion: 'Carga estimación desde Excel base64.', permisos: 'requerimientos.editar' },
  { modulo: 'Estimaciones', metodo: 'GET', ruta: '/api/estimaciones/{estimacion_id}', descripcion: 'Obtiene estimación.' },
  { modulo: 'Estimaciones', metodo: 'POST', ruta: '/api/estimaciones', descripcion: 'Crea estimación manual.', permisos: 'requerimientos.editar' },
  { modulo: 'Estimaciones', metodo: 'PUT', ruta: '/api/estimaciones/{estimacion_id}', descripcion: 'Actualiza estimación.', permisos: 'requerimientos.editar' },
  { modulo: 'Estimaciones', metodo: 'DELETE', ruta: '/api/estimaciones/{estimacion_id}', descripcion: 'Elimina estimación.', permisos: 'requerimientos.editar' },
  { modulo: 'Estimaciones', metodo: 'POST', ruta: '/api/estimaciones/{estimacion_id}/crear-tareas-hitss', descripcion: 'Crea Feature/HU/Tasks en Azure DevOps HITSS.', permisos: 'requerimientos.editar' },
  { modulo: 'Estimaciones', metodo: 'POST', ruta: '/api/estimaciones/{estimacion_id}/crear-tareas-epm', descripcion: 'Crea Tasks en Azure DevOps EPM usando HU padre.', permisos: 'requerimientos.editar' },

  { modulo: 'Azure DevOps', metodo: 'GET', ruta: '/api/azdo/config', descripcion: 'Obtiene configuración por target y jerarquía.', parametros: 'target=hitss|epm, squad_id, usuario_id' },
  { modulo: 'Azure DevOps', metodo: 'GET', ruta: '/api/azdo/config/all', descripcion: 'Lista configuraciones AzDO de la aplicación.' },
  { modulo: 'Azure DevOps', metodo: 'PUT', ruta: '/api/azdo/config', descripcion: 'Guarda configuración HITSS o EPM.', cuerpo: 'org_url, pat, default_project, sync_interval, target, squad_id, usuario_id' },
  { modulo: 'Azure DevOps', metodo: 'DELETE', ruta: '/api/azdo/config', descripcion: 'Elimina configuración por squad o usuario.', parametros: 'target=hitss|epm, squad_id, usuario_id' },
  { modulo: 'Azure DevOps', metodo: 'GET', ruta: '/api/azdo/test', descripcion: 'Prueba conexión AzDO.', parametros: 'target=hitss|epm, squad_id, usuario_id' },
  { modulo: 'Azure DevOps', metodo: 'GET', ruta: '/api/azdo/campos-requeridos', descripcion: 'Descubre campos requeridos para Feature, HU/PBI y Task.', parametros: 'target=hitss|epm, squad_id, usuario_id' },
  { modulo: 'Azure DevOps', metodo: 'GET', ruta: '/api/azdo/proyectos', descripcion: 'Lista proyectos AzDO.', parametros: 'target=hitss|epm, squad_id, usuario_id' },
  { modulo: 'Azure DevOps', metodo: 'GET', ruta: '/api/azdo/iteraciones', descripcion: 'Lista iteraciones del proyecto.', parametros: 'proyecto, target=hitss|epm, squad_id, usuario_id' },
  { modulo: 'Azure DevOps', metodo: 'GET', ruta: '/api/azdo/work-items', descripcion: 'Lista work items sincronizados.' },
  { modulo: 'Azure DevOps', metodo: 'GET', ruta: '/api/azdo/sync-log', descripcion: 'Lista histórico de sincronización.' },
  { modulo: 'Azure DevOps', metodo: 'POST', ruta: '/api/azdo/sync', descripcion: 'Sincroniza una iteración.', cuerpo: 'azdo_project, iteration_path, target' },

  { modulo: 'Soporte', metodo: 'GET', ruta: '/api/soporte/solicitudes-fabrica', descripcion: 'Lista solicitudes fábrica importadas.', permisos: 'soporte.solicitudes_fabrica.ver' },
  { modulo: 'Soporte', metodo: 'GET', ruta: '/api/soporte/solicitudes-fabrica/resumen', descripcion: 'Resumen ligero para dashboards.', permisos: 'soporte.solicitudes_fabrica.ver' },
  { modulo: 'Soporte', metodo: 'POST', ruta: '/api/soporte/solicitudes-fabrica/previsualizar', descripcion: 'Previsualiza Excel antes de sincronizar.', cuerpo: 'multipart archivo', permisos: 'soporte.solicitudes_fabrica.actualizar' },
  { modulo: 'Soporte', metodo: 'POST', ruta: '/api/soporte/solicitudes-fabrica/sincronizar', descripcion: 'Sincroniza solicitudes desde Excel.', cuerpo: 'multipart archivo', permisos: 'soporte.solicitudes_fabrica.actualizar' },
  { modulo: 'Soporte', metodo: 'GET', ruta: '/api/soporte/solicitudes-fabrica/sincronizaciones/{sync_id}/errores.csv', descripcion: 'Descarga errores de sincronización en CSV.', permisos: 'soporte.solicitudes_fabrica.ver' },

  { modulo: 'Personas', metodo: 'GET', ruta: '/api/personas/roles', descripcion: 'Lista roles de persona configurados.' },
  { modulo: 'Personas', metodo: 'GET', ruta: '/api/personas/duplicados', descripcion: 'Detecta personas duplicadas.' },
  { modulo: 'Personas', metodo: 'POST', ruta: '/api/personas/deduplicar', descripcion: 'Fusiona duplicados y actualiza referencias.' },
  { modulo: 'Personas', metodo: 'GET', ruta: '/api/personas', descripcion: 'Lista personas.' },
  { modulo: 'Personas', metodo: 'GET', ruta: '/api/personas/{persona_id}', descripcion: 'Obtiene persona.' },
  { modulo: 'Personas', metodo: 'POST', ruta: '/api/personas', descripcion: 'Crea persona.' },
  { modulo: 'Personas', metodo: 'PUT', ruta: '/api/personas/{persona_id}', descripcion: 'Actualiza persona.' },
  { modulo: 'Personas', metodo: 'DELETE', ruta: '/api/personas/{persona_id}', descripcion: 'Elimina persona.' },

  { modulo: 'Carga de trabajo', metodo: 'GET', ruta: '/api/asignaciones', descripcion: 'Lista asignaciones.' },
  { modulo: 'Carga de trabajo', metodo: 'GET', ruta: '/api/asignaciones/{asignacion_id}', descripcion: 'Obtiene asignación.' },
  { modulo: 'Carga de trabajo', metodo: 'POST', ruta: '/api/asignaciones', descripcion: 'Crea asignación.' },
  { modulo: 'Carga de trabajo', metodo: 'PUT', ruta: '/api/asignaciones/{asignacion_id}', descripcion: 'Actualiza asignación.' },
  { modulo: 'Carga de trabajo', metodo: 'PATCH', ruta: '/api/asignaciones/{asignacion_id}/prioridad', descripcion: 'Actualiza prioridad de asignación.' },
  { modulo: 'Carga de trabajo', metodo: 'DELETE', ruta: '/api/asignaciones/{asignacion_id}', descripcion: 'Elimina asignación.' },
  { modulo: 'Carga de trabajo', metodo: 'POST', ruta: '/api/asignaciones/sincronizar/{codigo_req}', descripcion: 'Sincroniza asignación desde requerimiento.' },
  { modulo: 'Carga de trabajo', metodo: 'GET', ruta: '/api/capacidades', descripcion: 'Lista capacidades.', parametros: 'mes opcional' },
  { modulo: 'Carga de trabajo', metodo: 'POST', ruta: '/api/capacidades', descripcion: 'Crea capacidad.' },
  { modulo: 'Carga de trabajo', metodo: 'PUT', ruta: '/api/capacidades/{capacidad_id}', descripcion: 'Actualiza capacidad.' },
  { modulo: 'Carga de trabajo', metodo: 'DELETE', ruta: '/api/capacidades/{capacidad_id}', descripcion: 'Elimina capacidad.' },
  { modulo: 'Carga de trabajo', metodo: 'GET', ruta: '/api/squads', descripcion: 'Lista squads.' },
  { modulo: 'Carga de trabajo', metodo: 'POST', ruta: '/api/squads', descripcion: 'Crea squad.' },
  { modulo: 'Carga de trabajo', metodo: 'PUT', ruta: '/api/squads/{squad_id}', descripcion: 'Actualiza squad.' },
  { modulo: 'Carga de trabajo', metodo: 'DELETE', ruta: '/api/squads/{squad_id}', descripcion: 'Elimina squad.' },

  { modulo: 'Catálogos', metodo: 'GET', ruta: '/api/tarifas', descripcion: 'Lista tarifas.' },
  { modulo: 'Catálogos', metodo: 'POST', ruta: '/api/tarifas', descripcion: 'Crea tarifa.' },
  { modulo: 'Catálogos', metodo: 'PUT', ruta: '/api/tarifas/{tarifa_id}', descripcion: 'Actualiza tarifa.' },
  { modulo: 'Catálogos', metodo: 'DELETE', ruta: '/api/tarifas/{tarifa_id}', descripcion: 'Elimina tarifa.' },
  { modulo: 'Catálogos', metodo: 'GET', ruta: '/api/festivos', descripcion: 'Lista festivos.' },
  { modulo: 'Catálogos', metodo: 'POST', ruta: '/api/festivos', descripcion: 'Crea festivo.' },
  { modulo: 'Catálogos', metodo: 'DELETE', ruta: '/api/festivos/{festivo_id}', descripcion: 'Elimina festivo.' },
  { modulo: 'Catálogos', metodo: 'GET', ruta: '/api/categorias', descripcion: 'Lista categorías.' },
  { modulo: 'Catálogos', metodo: 'POST', ruta: '/api/categorias', descripcion: 'Crea categoría.' },
  { modulo: 'Catálogos', metodo: 'PUT', ruta: '/api/categorias/{categoria_id}', descripcion: 'Actualiza categoría.' },
  { modulo: 'Catálogos', metodo: 'DELETE', ruta: '/api/categorias/{categoria_id}', descripcion: 'Elimina categoría.' },
  { modulo: 'Catálogos', metodo: 'GET', ruta: '/api/actas', descripcion: 'Lista actas.' },
  { modulo: 'Catálogos', metodo: 'POST', ruta: '/api/actas', descripcion: 'Crea acta.' },
  { modulo: 'Catálogos', metodo: 'PUT', ruta: '/api/actas/{acta_id}', descripcion: 'Actualiza acta.' },
  { modulo: 'Catálogos', metodo: 'DELETE', ruta: '/api/actas/{acta_id}', descripcion: 'Elimina acta.' },
  { modulo: 'Configuración', metodo: 'GET', ruta: '/api/configuracion', descripcion: 'Lista parámetros de configuración.' },
  { modulo: 'Configuración', metodo: 'PUT', ruta: '/api/configuracion/{clave}', descripcion: 'Crea o actualiza parámetro.' },
  { modulo: 'Configuración', metodo: 'DELETE', ruta: '/api/configuracion/{clave}', descripcion: 'Elimina parámetro.' },

  { modulo: 'Importación', metodo: 'POST', ruta: '/api/importacion/excel', descripcion: 'Importa datos desde Excel.', cuerpo: 'multipart archivo' },
  { modulo: 'Importación', metodo: 'GET', ruta: '/api/importacion/excel/plantilla', descripcion: 'Descarga plantilla Excel.' },
  { modulo: 'Importación', metodo: 'POST', ruta: '/api/importacion/excel/previsualizar', descripcion: 'Previsualiza importación Excel.', cuerpo: 'multipart archivo' },

  { modulo: 'Dashboards y reportes', metodo: 'GET', ruta: '/api/dashboard/consolidado', descripcion: 'Dashboard consolidado.' },
  { modulo: 'Dashboards y reportes', metodo: 'GET', ruta: '/api/cifras/estado', descripcion: 'Cifras por estado.' },
  { modulo: 'Dashboards y reportes', metodo: 'GET', ruta: '/api/cifras/squad', descripcion: 'Cifras por squad.' },
  { modulo: 'Dashboards y reportes', metodo: 'GET', ruta: '/api/cifras/ans', descripcion: 'Cifras de ANS.' },
  { modulo: 'Dashboards y reportes', metodo: 'GET', ruta: '/api/cifras/liquidacion', descripcion: 'Cifras de liquidación.' },
  { modulo: 'Dashboards y reportes', metodo: 'GET', ruta: '/api/reportes/equipo', descripcion: 'Reporte de equipo.' },
  { modulo: 'Dashboards y reportes', metodo: 'GET', ruta: '/api/reportes/roadmap', descripcion: 'Reporte de roadmap.' },
  { modulo: 'Bitácora', metodo: 'GET', ruta: '/api/bitacora', descripcion: 'Lista eventos de bitácora.', parametros: 'entidad_id opcional' },
  { modulo: 'Bitácora', metodo: 'DELETE', ruta: '/api/bitacora/{evento_id}', descripcion: 'Elimina evento de bitácora.' },

  { modulo: 'Integración externa', metodo: 'GET', ruta: '/api/integracion/entregas', descripcion: 'Entregas pendientes para Power Automate. Auth: X-API-Key.', parametros: 'aplicacion opcional' },
  { modulo: 'Integración externa', metodo: 'GET', ruta: '/api/integracion/requerimientos', descripcion: 'Requerimientos para Power Automate. Auth: X-API-Key independiente.', parametros: 'aplicacion y estado opcionales' },
  { modulo: 'Integración externa', metodo: 'GET', ruta: '/api/integracion/solicitudes', descripcion: 'Fecha y hora de solicitud, Código SC, Código REQ, Squad, Estado, ANS ACTA, fecha real de entrega de estimaciones y horas estimadas. Auth: X-API-Key independiente (API_KEY_SOLICITUDES).', parametros: 'aplicacion opcional' },
  { modulo: 'Integración externa', metodo: 'GET', ruta: '/api/integracion/solicitudes-entregas', descripcion: 'Entregas aplanadas: Código SC, Código REQ, N° Entrega, Horas, F. Comprometida, F. Real, Estado, Mes de aprobación, ANS (de la entrega), Garantía y N° Garantía (fechas sin hora). Auth: X-API-Key independiente (API_KEY_SOLICITUDES).', parametros: 'aplicacion opcional' },
]

/**
 * Excepcion categorica ADR-0007: el color identifica el verbo, no un estado.
 * La forma la da `.chip` via <Chip tono="categoria">; aqui solo el par bg/text.
 */
export const metodoClase: Record<Metodo, string> = {
  GET: 'bg-emerald-50 text-emerald-700',
  POST: 'bg-blue-50 text-blue-700',
  PUT: 'bg-amber-50 text-amber-700',
  PATCH: 'bg-purple-50 text-purple-700',
  DELETE: 'bg-red-50 text-red-700',
}
