export const ESTADOS_REQUERIMIENTO = [
  'ESTIMACION EN CURSO POR HITSS',
  'ESTIMACION EN ESPERA DE APROBACION POR EPM',
  'ESTIMACION APROBADA POR LT',
  'ESTIMACION APROBADA ENTREGA PENDIENTE',
  'ENTREGA CARGADA',
  'ENTREGA NO CARGADA',
  'CONTROL DE CAMBIOS',
  'REQUERIMIENTO DEVUELTO A EPM',
  'REQUERIMIENTO SUSPENDIDO POR EPM',
  'REQUERIMIENTO CANCELADO POR EPM',
  'REQUERIMIENTO CANCELADO',
  'REQUERIMIENTO REEMPLAZADO',
]

export const ESTADOS_ENTREGA = [
  'PENDIENTE',
  'EN ESPERA DE APROBACION',
  'ENTREGA CARGADA',
  'ENTREGA NO CARGADA',
  'APROBADA',
  'RECHAZADA',
  'EN GARANTIA',
]

export const TIPOS_COSTO = ['TYM', 'FIJO']

export const ROLES_USUARIO = ['superadmin', 'admin_app', 'editor', 'viewer']
